# Site settings
title: Black Box of Magical Bits 
email: wfrisby@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Wes Frisby's Blog 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wfrisby.github.io" # the base hostname & protocol for your site
twitter_username: wesfrisby
github_username:  wfrisby

# Build settings
markdown: kramdown
